---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbench
  labels:
    app: bench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: <storageclass-name>
  volumeMode: Filesystem
